#!/usr/bin/env python3
"""
This module provides an asynchronous comprehension that collects
random float numbers generated by an async generator into a list.
"""

from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Collects 10 random float numbers from an asynchronous generator into a list
    Returns:
        List[float]: A list containing 10 random float numbers between 0 and 10
    """
    return [num async for num in async_generator()]
